#!/bin/bash

image=jester

###########

get_container_list() {
	docker ps --all --filter "$1" --format "{{.Names}}"
}

###########

for container in $(get_container_list "ancestor=$image"); do
	docker stop "$container"
	if [[ $(get_container_list "name=$container") ]]; then
		docker rm --volumes --force "$container"
	fi
done

docker rmi --force "$image"

echo -e "\e[1;32mAll $image images and containers have been removed" >&2
