#!/bin/bash

image=jester
task=$(basename $0)
container=$image.$task
volume_path=/opt/$image

docker build --tag=$image .
docker run \
	--interactive \
	--tty \
	--rm \
	--user node \
	--volume="$(pwd):$volume_path" \
	--name=$container \
	$image \
		/bin/bash
